const type = "messageTypes.";
export const SET_MESSAGES = type + "SET_MESSAGES";
export const GET_MESSAGE_BY_ID = type + "GET_MESSAGE_BY_ID";
export const GET_MESSAGES_BY_GROUP_ID = type + "GET_MESSAGES_BY_GROUP_ID";
export const GET_MESSAGES_BY_GROUP_ID_SUCCESS =
  type + "GET_MESSAGES_BY_GROUP_ID_SUCCESS";
export const GET_MESSAGES_BY_GROUP_ID_FAILURE =
  type + "GET_MESSAGES_BY_GROUP_ID_FAILURE";
export const ADD_NEW_MESSAGE = type + "ADD_NEW_MESSAGE";
export const ADD_NEW_MESSAGE_SUCCESS = type + "ADD_NEW_MESSAGE_SUCCESS";
export const ADD_NEW_MESSAGE_FAILURE = type + "ADD_NEW_MESSAGE_FAILURE";
export const UPDATE_MESSAGE = type + "UPDATE_MESSAGE";
export const UPDATE_MESSAGE_SUCCESS = type + "UPDATE_MESSAGE_SUCCESS";
export const UPDATE_MESSAGE_FAILURE = type + "UPDATE_MESSAGE_FAILURE";
export const DELETE_MESSAGE = type + "DELETE_MESSAGE";
export const DELETE_MESSAGE_SUCCESS = type + "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILURE = type + "DELETE_MESSAGE_FAILURE";
